import jsPDF from 'jspdf';
import { Lesson } from '@/types';

export const exportToPDF = (lesson: Lesson) => {
    try {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const margin = 20;
        const contentWidth = pageWidth - (margin * 2);

        // Header with branding
        doc.setFillColor(99, 102, 241); // Primary color
        doc.rect(0, 0, pageWidth, 35, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.setFont('helvetica', 'bold');
        doc.text('Edu-Spark AI', margin, 20);

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text('AI-Powered Lesson Planning Platform', margin, 28);

        // Title Section
        let yPos = 50;
        doc.setTextColor(40, 40, 40);
        doc.setFontSize(20);
        doc.setFont('helvetica', 'bold');
        const titleLines = doc.splitTextToSize(lesson.title, contentWidth);
        doc.text(titleLines, margin, yPos);
        yPos += (titleLines.length * 8) + 5;

        // Metadata bar
        doc.setFillColor(245, 245, 245);
        doc.rect(margin, yPos, contentWidth, 20, 'F');

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.setFont('helvetica', 'normal');
        doc.text(`Subject: ${lesson.subject}`, margin + 5, yPos + 8);
        doc.text(`Grade: ${lesson.grade}`, margin + 70, yPos + 8);
        doc.text(`Topic: ${lesson.topic}`, margin + 5, yPos + 15);

        yPos += 30;

        // Content Section
        doc.setFontSize(14);
        doc.setTextColor(40, 40, 40);
        doc.setFont('helvetica', 'bold');
        doc.text('Lesson Content', margin, yPos);
        yPos += 8;

        // Draw separator line
        doc.setDrawColor(99, 102, 241);
        doc.setLineWidth(0.5);
        doc.line(margin, yPos, pageWidth - margin, yPos);
        yPos += 8;

        // Parse and format content
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);

        // Strip HTML and format content
        let plainText = lesson.content
            .replace(/<h1[^>]*>(.*?)<\/h1>/gi, '\n\n=== $1 ===\n\n')
            .replace(/<h2[^>]*>(.*?)<\/h2>/gi, '\n\n--- $1 ---\n\n')
            .replace(/<h3[^>]*>(.*?)<\/h3>/gi, '\n\n• $1\n\n')
            .replace(/<strong[^>]*>(.*?)<\/strong>/gi, '$1')
            .replace(/<b[^>]*>(.*?)<\/b>/gi, '$1')
            .replace(/<em[^>]*>(.*?)<\/em>/gi, '$1')
            .replace(/<i[^>]*>(.*?)<\/i>/gi, '$1')
            .replace(/<li[^>]*>(.*?)<\/li>/gi, '  • $1\n')
            .replace(/<ul[^>]*>/gi, '\n')
            .replace(/<\/ul>/gi, '\n')
            .replace(/<ol[^>]*>/gi, '\n')
            .replace(/<\/ol>/gi, '\n')
            .replace(/<p[^>]*>/gi, '')
            .replace(/<\/p>/gi, '\n\n')
            .replace(/<br\s*\/?>/gi, '\n')
            .replace(/<[^>]+>/g, '')
            .replace(/&nbsp;/g, ' ')
            .replace(/&amp;/g, '&')
            .replace(/&lt;/g, '<')
            .replace(/&gt;/g, '>')
            .replace(/&quot;/g, '"')
            .replace(/\n\s*\n\s*\n/g, '\n\n')
            .trim();

        const contentLines = doc.splitTextToSize(plainText, contentWidth);

        // Add content with page breaks
        for (let i = 0; i < contentLines.length; i++) {
            if (yPos > pageHeight - 30) {
                doc.addPage();
                yPos = 20;
            }
            doc.text(contentLines[i], margin, yPos);
            yPos += 6;
        }

        // Footer on all pages
        const totalPages = doc.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
            doc.setPage(i);

            // Footer background
            doc.setFillColor(245, 245, 245);
            doc.rect(0, pageHeight - 15, pageWidth, 15, 'F');

            // Footer text
            doc.setFontSize(8);
            doc.setTextColor(120, 120, 120);
            doc.setFont('helvetica', 'normal');
            doc.text(
                `Generated by Edu-Spark AI on ${new Date().toLocaleDateString()}`,
                margin,
                pageHeight - 8
            );
            doc.text(
                `Page ${i} of ${totalPages}`,
                pageWidth - margin - 20,
                pageHeight - 8
            );
        }

        // Save the PDF
        const filename = `${lesson.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`;
        doc.save(filename);
        return true;
    } catch (error) {
        console.error('PDF Export Error:', error);
        return false;
    }
};

export const createGoogleDoc = async (lesson: Lesson) => {
    try {
        const response = await fetch('/api/export/google-doc', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                title: lesson.title,
                content: lesson.content
            })
        });

        if (response.status === 401) {
            // Need to authenticate
            const authResponse = await fetch('/api/auth/google');
            const authData = await authResponse.json();

            return {
                success: false,
                authUrl: authData.url,
                message: 'Please connect your Google Account'
            };
        }

        const data = await response.json();

        if (!response.ok) {
            throw new Error(data.error || 'Failed to create doc');
        }

        return {
            success: true,
            url: data.url,
            message: 'Google Doc created successfully'
        };
    } catch (error: any) {
        return {
            success: false,
            message: error.message || 'Error creating Google Doc'
        };
    }
};

export const shareLesson = async (lesson: Lesson, emails: string[]) => {
    // Mock email sharing
    return new Promise<{ success: boolean }>((resolve) => {
        setTimeout(() => {
            console.log(`Sharing lesson ${lesson.id} with ${emails.join(', ')}`);
            resolve({ success: true });
        }, 1000);
    });
};

// New function for sending email with PDF attachment
export const sendLessonEmail = async (lesson: Lesson, recipients: string[], message?: string) => {
    try {
        const response = await fetch('/api/share/lesson-pdf', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                lessonId: lesson.id,
                lessonTitle: lesson.title,
                lessonContent: lesson.content,
                lessonMetadata: {
                    subject: lesson.subject,
                    grade: lesson.grade,
                    topic: lesson.topic
                },
                recipients,
                customMessage: message
            })
        });

        const data = await response.json();

        if (!response.ok) {
            throw new Error(data.error || 'Failed to send email');
        }

        return {
            success: true,
            message: data.message || 'Email sent successfully',
            preview: data.preview // For test emails
        };
    } catch (error: any) {
        return {
            success: false,
            message: error.message || 'Error sending email'
        };
    }
};
